PREFIX schema: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX civ: <https://iisg.amsterdam/id/civ/>
PREFIX civvoc: <https://iisg.amsterdam/id/civ/vocab/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX hsnocc: <https://iisg.amsterdam/resource/hsn/occupation/vocab/code/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX hist: <http://rdf.histograph.io/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>


SELECT  ?districtlabel ?category ?share ?wkt ?wktTooltip ?wktColor ?mapEndpoint WHERE {
  {
    SELECT

      ?districtlabel  (xsd:float(?deaths)/xsd:float(?n_birth) * 100 AS ?share) ?wkt 

    WHERE {
  
       SELECT  
  
      (sum(?hasDeath) as ?deaths) (count(?birth) as ?n_birth) ?category ?districtlabel ?wkt 
   
    WHERE {
      ?birth a civ:Birth .
      ?birth civvoc:event_districtName ?wijk .
      ?wijk rdfs:label ?districtlabel .
        BIND(EXISTS{?birth civ:linkedToDeath ?death} AS ?hasDeath )
  
      #get districtlabels from adamnet
      ?adamneturi a  hist:district .
      ?adamneturi rdfs:label ?label .
      ?adamneturi geo:hasGeometry/geo:asWKT ?wkt .
        FILTER(?label = ?districtlabel)
     
        }
    }}
    BIND(xsd:int(?share) as ?share2)
    BIND(concat(?districtlabel,'_',STR(?share2),'%') as ?wktTooltip)
    BIND ( IF ( ?share > 20, 1, IF ( ?share > 15, 0.65, IF (?share > 10, 0.50, IF(?share > 5, 0.35,   0.1 )))) AS ?category)
    BIND(concat('YlOrRd,', (?category)) as ?wktColor) 
    BIND("https://mapwarper.net/maps/wms/29156?request=GetCapabilities&service=WMS&version=1.1.1" as ?mapEndpoint)

  }
 ORDER BY DESC(?share)
   

  
