PREFIX schema: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX civ: <https://iisg.amsterdam/id/civ/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX hsnocc: <https://iisg.amsterdam/resource/hsn/occupation/vocab/code/>


SELECT   ?birth (sum(?hasDeath) as ?n_deaths)

WHERE {
  
 ?birth a civ:Birth .
 BIND(EXISTS{?birth civ:linkedToDeath ?death} AS ?hasDeath )
  
    }
 ORDER BY DESC(?n_deaths)
   

  
