#+ summary: select all possible variables of migrants with hisclass and geolocation
#+ tags:
#+      - admissies
#+      - journeymen
#+      - hisclass
#+      - hisco
#+      - geolocation


PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
prefix geo: <http://www.opengis.net/ont/geosparql#>
prefix admissie: <https://iisg.amsterdam/Admissieregisters_Haarlem/vocab/>
prefix hsnvocab: <https://iisg.amsterdam/hsn2013a/vocab/>
prefix hsn: <https://iisg.amsterdam/hsn2013a/>

SELECT * WHERE {
     ?sub admissie:ID ?ID .
     ?sub admissie:Sex_principal ?sex .
     ?sub admissie:Year ?year .
     ?sub admissie:Month ?month .
 
  OPTIONAL{
     ?sub admissie:Origin ?origin .
     ?origin geo:hasGeometry/ geo:asWKT ?wkt}.

  OPTIONAL{
     ?sub admissie:Occupation_man ?occman}
  
  OPTIONAL{
     ?sub admissie:Occupation_wife ?occwife}
  
  OPTIONAL{
     ?sub admissie:Married ?married}
    
  OPTIONAL{
     ?sub admissie:Children ?children}
  
  OPTIONAL{
     ?sub admissie:Birthplace ?birthplace} 
  
  OPTIONAL{
     ?sub admissie:dist_birth_origin ?distance_birth_origin}

  OPTIONAL{
     ?sub hsnvocab:occupationalTitle ?occ2 .
     ?hisco skos:member ?occ2 .
     ?hisco skos:inScheme ?scheme .
     ?hisco skos:notation ?hisconr.
     ?occ2 hsn:hisclass ?hisclass }

 }
