# simple count by age over two datasets
# note that age in scotlang != integer, hence the bind

PREFIX nappdim: <http://data.socialhistory.org/vocab/napp/dimension/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT (COUNT(?brit) AS ?nbrits) ?nage

FROM <http://data.socialhistory.org/resource/napp/dataset/scotland1881>
FROM <http://data.socialhistory.org/resource/napp/dataset/englandwales1881>

WHERE {
    ?brit nappdim:AGE ?age.
    BIND(xsd:integer(?age) as ?nage)
}

GROUP BY ?nage
ORDER BY ?nage
