# occupational status by occupation in canada 1891
# same as occstatus_by_birthyear from engwal 1881
# but using slightly more involved occupational coding

# occhisco to hisco to hiscam

SELECT *

FROM <http://data.socialhistory.org/resource/napp/dataset/canada1891>
FROM <http://data.socialhistory.org/vocab/hisco/>

WHERE {
    ?person napp-dimension:OCCHISCO ?occhisco . 
    ?occhisco (skos:closeMatch|skos:exactMatch) ?hisco .
    ?hiscoentry hisco:hiscoCode ?hisco . 
    ?hiscoentry hiscam:hiscamValue ?hiscam .
    ?hiscoentry skos:inScheme hiscam:cahiscam .
    # ?hisco skos:prefLabel ?label .
}
LIMIT 100