# occupational status by occupation in canada 1891
# same as occstatus_by_birthyear from engwal 1881
# but using slightly more involved occupational coding

# person-level obs combined with birthyear-gdp

PREFIX napp-dimension: <http://data.socialhistory.org/vocab/napp/dimension/>
PREFIX cliomsr: <http://data.socialhistory.org/resource/clio/measure/>
PREFIX clio: <http://data.socialhistory.org/resource/clio/>
PREFIX clioctr: <http://data.socialhistory.org/resource/clio/country/>
PREFIX sdmxd: <http://purl.org/linked-data/sdmx/2009/dimension#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT *

FROM <http://data.socialhistory.org/resource/napp/dataset/canada1891>
FROM <http://data.socialhistory.org/ns/resource/GDP_Capita-historical/assertion/fd2ce578/2016-08-25T14:25>

WHERE{
    ?person napp-dimension:OCCHISCO ?occhisco .
    ?person napp-dimension:AGE ?age .
    ?person napp-dimension:YEAR ?censusyear .
    
    OPTIONAL{
        ?country cliomsr:GDP_per_Capita ?gdppc .
        ?country sdmxd:refArea ?refarea . 
        ?refarea clio:ccode clioctr:124.0 .
        ?country sdmxd:refPeriod ?year
        FILTER(xsd:int(str(?year)) = (?censusyear - ?age))        
    }
}

LIMIT 100
