# occupational status by occupation in canada 1891
# same as occstatus_by_birthyear from engwal 1881
# but using slightly more involved occupational coding

# gdp series

SELECT *

FROM <http://data.socialhistory.org/resource/gdppc/assertion/5343176a06654392f04b0dcf163d1f1f0f65ffce/2016-01-21T16:30:48.081802>
WHERE {
    ?dataset clioprop:indicator clioind:GDPPC1990GKD .
    ?dataset sdmx-dimension:refArea clioctr:124 .
    ?dataset sdmx-measure:obsValue ?gdppc .
    ?dataset sdmx-dimension:refPeriod ?year .
}

ORDER BY ?year
LIMIT 100