# occupational status by occupation in canada 1891
# same as occstatus_by_birthyear from engwal 1881
# but using slightly more involved occupational coding

# get average hiscam value and gdp in that birthyear 
# for sumstats or visualisation

SELECT AVG(?hiscam) AS ?meanhiscam ?year ?gdppc

FROM <http://data.socialhistory.org/resource/napp/dataset/canada1891>
FROM <http://qber.data2semantics.org/vocab/ocs/hisco/>
FROM <http://data.socialhistory.org/resource/gdppc/assertion/5343176a06654392f04b0dcf163d1f1f0f65ffce/2015-12-01T16:05:28.244606>

WHERE {
    ?dataset clioprop:indicator clioind:GDPPC1990GKD .
    ?dataset sdmx-dimension:refArea clioctr:124 .
    ?dataset sdmx-measure:obsValue ?gdppc .
    ?dataset sdmx-dimension:refPeriod ?year .
    FILTER(xsd:int(str(?year)) < 1892) .
    
    OPTIONAL{
        ?person napp-dimension:OCCHISCO ?occhisco .
        ?occhisco (skos:closeMatch|skos:exactMatch) ?hisco .
        ?hiscoentry hiscocat:hiscoCode ?hisco . 
        ?hiscoentry hiscam:hiscamValue ?hiscam .
        ?hisco skos:prefLabel ?label .
        ?hiscoentry skos:inScheme hiscam:cahiscam .
        
		?person napp-dimension:AGE ?age .
        ?person napp-dimension:YEAR ?censusyear .
        FILTER((?censusyear - ?age) = (xsd:int(str(?year))))
        FILTER(?occhisco != 99999).
        FILTER(?age != 999).
        FILTER(?age > 12).

    }
}
ORDER BY ?year
LIMIT 1000