# occupational status by occupation in canada 1891
# same as occstatus_by_birthyear from engwal 1881
# but using slightly more involved occupational coding

# gdp series

SELECT *

FROM <http://data.socialhistory.org/resource/clio/>

WHERE {
    ?dataset clioprop:indicator clioind:GDPPC1990GKD .
    ?dataset sdmx-dimension:refArea clioctr:124 .
    ?dataset sdmx-measure:obsValue ?gdppc .
    ?dataset sdmx-dimension:refPeriod ?year .
}

ORDER BY ?year
LIMIT 100