# occupational status by occupation in canada 1891
# same as occstatus_by_birthyear from engwal 1881
# but using slightly more involved occupational coding

# occhisco to hisco to hiscam

PREFIX napp-dimension: <http://data.socialhistory.org/vocab/napp/dimension/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX hiscam: <http://data.socialhistory.org/resource/hiscam/>
PREFIX sdmxd: <http://purl.org/linked-data/sdmx/2009/dimension#>

SELECT *

WHERE {
    ?person napp-dimension:OCCHISCO ?occhisco . 
    ?occhisco (skos:exactMatch|skos:closeMatch) ?hisco .
    ?hiscam_entry hiscam:hisco ?hisco .
    ?hiscam_entry hiscam:value ?hiscam .
    ?hisco_in_hiscam sdmxd:refArea <http://sws.geonames.org/6251999/> .
}
LIMIT 100