# occupational status by occupation in canada 1891
# same as occstatus_by_birthyear from engwal 1881
# but using slightly more involved occupational coding

# person-level observations in canada 1891

SELECT * 

FROM <http://data.socialhistory.org/resource/napp/dataset/canada1891>
FROM <http://qber.data2semantics.org/vocab/ocs/hisco/>

WHERE {
    ?person napp-dimension:OCCHISCO ?occhisco .
    ?person napp-dimension:AGE ?age .
    ?person napp-dimension:YEAR ?censusyear .
    BIND(?censusyear - ?age as ?birthyear)
}

LIMIT 100