# occupational status by occupation in canada 1891
# same as occstatus_by_birthyear from engwal 1881
# but using slightly more involved occupational coding

# person-level obs combined with birthyear-gdp

SELECT *

FROM <http://data.socialhistory.org/resource/napp/dataset/canada1891>
FROM <http://data.socialhistory.org/resource/clio/>

WHERE{
    ?person napp-dimension:OCCHISCO ?occhisco .
    ?person napp-dimension:AGE ?age .
    ?person napp-dimension:YEAR ?censusyear .
    
    OPTIONAL{
        ?dataset clioprop:indicator clioind:GDPPC1990GKD .
        ?dataset sdmx-dimension:refArea clioctr:124 .
        ?dataset sdmx-measure:obsValue ?gdppc .
        ?dataset sdmx-dimension:refPeriod ?year .
        FILTER(xsd:int(str(?year)) = (?censusyear - ?age))        
    }
}

LIMIT 100