PREFIX canfam: <http://data.socialhistory.org/vocab/canfam/dimension/>
PREFIX literate: <http://data.socialhistory.org/resource/canfam/canread/>

SELECT (COUNT(?literate) AS ?n_literate) ?age 

FROM <http://data.socialhistory.org/resource/canfam/dataset/canada1901> 

WHERE {
    ?literate canfam:canread literate:Y.
    ?literate canfam:ageyr ?age
}

GROUP BY ?age
ORDER BY DESC(?age)