# tabulate religions

PREFIX candim: <http://data.socialhistory.org/vocab/canfam/dimension/>

SELECT (COUNT(?personid) AS ?nreligion) ?religion 

FROM <http://data.socialhistory.org/resource/canfam/dataset/canada1901>

WHERE {
  ?personid  candim:religio2 ?religion .
}

GROUP BY ?religion
ORDER BY DESC(?nreligion)

# rc > methodist > presb > anglican