#---- qry3 ----#
# list all marital statuses
PREFIX candim: <http://data.socialhistory.org/vocab/canfam/dimension/>

SELECT DISTINCT ?maritalstatus 
FROM <http://data.socialhistory.org/resource/canfam/dataset/canada1901>
WHERE {
  ?personid candim:marst ?maritalstatus
}
