# HULK SMASH!

PREFIX candim: <http://data.socialhistory.org/vocab/canfam/dimension/>
PREFIX marst: <http://data.socialhistory.org/resource/canfam/marst/>
PREFIX sex: <http://data.socialhistory.org/resource/canfam/sex/>
PREFIX relhead2: <http://data.socialhistory.org/resource/canfam/relhead2/>
PREFIX aukes-religion: <http://data.socialhistory.org/resource/canfam/auke/religion/>

SELECT * 

FROM <http://data.socialhistory.org/resource/canfam/dataset/canada1901>
FROM <http://data.socialhistory.org/resource/canfam/auke>

WHERE {
    ?groomid candim:marst marst:M .
    ?groomid candim:sex sex:M .
    ?groomid candim:relhead2 relhead2:101 .
    ?groomid candim:hhdid ?hhdid .
    ?groomid candim:religio2 ?groomreligion.
    ?groomreligion aukes-religion: ?dgroomrel . 
    
    # ?groomreligion rdf:value ?groomreligionvalue . 
    # BIND(if(?groomreligionvalue < 20, "catholic", "other") as ?dgroomrel) .
    
    OPTIONAL {
        ?brideid candim:marst marst:M .
        ?brideid candim:sex sex:F .
        ?brideid candim:relhead2 relhead2:201 .
        ?brideid candim:hhdid ?hhdid .
        ?brideid candim:religio2 ?bridereligion.
        ?bridereligion aukes-religion: ?dbriderel . 
        
        # ?bridereligion rdf:value ?bridereligionvalue . 
        # BIND(if(?bridereligionvalue < 20, "catholic", "other") as ?dbriderel) .
    }
}