#----- religious intermarriage ----#
# following doi:10.1016/j.eeh.2014.11.002
# marriages between roman catholics and "others" 
# may not be the most useful scheme for canada, but good for now
# though arguably of interest to add to interpretation of Ferihough et al's estimates
# from canfam because the current napp data

# count number of spouses because the exact number of 
# results in query 8 (10000)

PREFIX candim: <http://data.socialhistory.org/vocab/canfam/dimension/>
PREFIX relhead2: <http://data.socialhistory.org/resource/canfam/relhead2/>
PREFIX sex: <http://data.socialhistory.org/resource/canfam/sex/>
PREFIX marst: <http://data.socialhistory.org/resource/canfam/marst/>

SELECT (COUNT(?hhid) AS ?nhh)

FROM <http://data.socialhistory.org/resource/canfam/dataset/canada1901>

WHERE{
    ?personid candim:hhdid ?hhid . 
    ?personid candim:relhead2 relhead2:201 .
    ?personid candim:sex sex:F .
    ?personid candim:marst marst:M .
}

# this suggests there should be some 40000 female spouses 
# and each should also have a household head, so you'd expect
# about 40000 results in query 8...
# => fixed in virtuoso.ini