
#+ summary: taxable wealth, assets, debts, and investments of catasto households
#+ tags:
#+      - catasto
#+      - wealth
#+      - debts

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX catastodim: <https://iisg.amsterdam/catasto/dimension/>
PREFIX catasto: <https://iisg.amsterdam/catasto/>

SELECT * WHERE {
  ?sub a catasto:household .
  ?sub catastodim:NOMFAM ?familyname .
  ?sub catastodim:FORTUNE ?taxablewealth .
  ?sub catastodim:DEDUCT ?debt .
  ?sub catastodim:TOTAL ?valueofassets .
  ?sub catastodim:CREANCE ?commercialinvestments .
  ?sub catastodim:CREDPUB ?publicinvestments .
  
  }
