#+ summary: Average wealth, investments, and debt by householdsize
#+ tags:
#+      - catasto
#+      - households
#+      - wealth
#+      - debt

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX catastodim: <https://iisg.amsterdam/catasto/dimension/>
PREFIX catasto: <https://iisg.amsterdam/catasto/>
PREFIX relationcode: <https://iisg.amsterdam/catasto/code/relationToHead/>

SELECT ?householdsize (count(?sub) as ?n_hh) (avg(?wealth) as ?avg_wealth) (avg(?debt) as ?avg_debt) (avg(?pubcred + ?privcred) as ?avg_investments) 
WHERE { SELECT  (count(?members) as ?householdsize) ?wealth ?sub ?debt ?pubcred ?privcred

WHERE {
 
?sub catastodim:householdMember ?members ;
     catastodim:TOTAL ?wealth ;
     catastodim:DEDUCT ?debt ;
     catastodim:CREANCE ?pubcred ;
     catastodim:CREDPUB ?privcred .
}
}
  
ORDER BY  (?householdsize)
LIMIT 16 # to filter out household sizes with N < 100
