#+ summary: individual apprentices listed in catasto
#+ tags:
#+      - catasto
#+      - apprentices

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX catastodim: <https://iisg.amsterdam/catasto/dimension/>
PREFIX catasto: <https://iisg.amsterdam/catasto/>
PREFIX relationcode: <https://iisg.amsterdam/catasto/code/relationToHead/>

SELECT  ?apprentice  ?household ?occupation ?occupation_head
WHERE {
 
  ?apprentice catastodim:relationToHead relationcode:77 .
  ?apprentice catastodim:inHousehold ?household .
  ?household catastodim:METIER ?occupation .
  ?occupation skos:prefLabel ?occupation_head .
  
  FILTER(lang(?occupation_head)="en")

        
} 

