#+ summary: basic clio query with country param
#+ tags:
#+    - education
#+    - clio-infra

PREFIX cliomsr: <http://data.socialhistory.org/resource/clio/measure/>
PREFIX sdmxd: <http://purl.org/linked-data/sdmx/2009/dimension#>

SELECT ?year ?educ
FROM <http://data.socialhistory.org/resource/Average_years_education-historical/assertion/0ba1f4de/2016-11-01T12:18>

WHERE {
    ?obs sdmxd:refArea ?_country . 
    ?obs sdmxd:refPeriod ?year .
    ?obs cliomsr:Average_Years_of_Education ?educ .
}
