#+ summary: ClioInfra query that underpins the visualisations of the new website.
#+
#+ endpoint: http://virtuoso.clariah-sdh.eculture.labs.vu.nl/sparql
#+ tags:
#+    - clio-infra
#+ enumerate:
#+   - _area_iri
#+   - _measure_iri 

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX sdmx-dimension: <http://purl.org/linked-data/sdmx/2009/dimension#>
SELECT ?year ?value WHERE {
  ?obs sdmx-dimension:refArea ?_area_iri .
  ?obs sdmx-dimension:refPeriod ?year .
  ?_measure_iri a qb:MeasureProperty.
  ?obs ?_measure_iri ?value .
}
