#+ summary: basic clio query with country param
#+ tags:
#+    - education
#+    - clio-infra

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX cliodim: <https://iisg.amsterdam/clio/dimension/>
prefix sdmxdim: <http://purl.org/linked-data/sdmx/2009/dimension#>

select ?year ?educ where {
  ?obs sdmxdim:refArea ?_country .
  ?obs sdmxdim:refPeriod ?year .
  ?obs cliodim:Average_Years_of_Education ?educ .
}