#+ summary: Query for a specific person (Posthumus) 
#+ tags:
#+      - DBpedia

# endpoint is http://dbpedia.org/sparql
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

SELECT *
WHERE {
  ?s foaf:name ?name .
  ?s rdf:type foaf:Person .
  BIND (fn:lower-case(?name) AS ?s_name) .
FILTER(?s_name = "nicolaas wilhelmus posthumus")
} 
LIMIT 10
