#+ summary: All variables in the hub and the datasets using them
#+ pagination: 100
#+ tags:
#+      - overview

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX np: <http://www.nanopub.org/nschema#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX example: <http://www.example.org/rdf#>
PREFIX qb: <http://purl.org/linked-data/cube#>

SELECT DISTINCT ?source_dimension (COUNT(?dimension_value) AS ?count) (MIN(?dimension_value) AS ?min) (MAX(?dimension_value) AS ?max) WHERE {
{
  ?source_np np:hasAssertion ?source_assertion .
  GRAPH ?source_assertion {
   ?_sourcedataset_iri qb:structure/qb:component/(qb:dimension|qb:measure) ?source_dimension .
   ?observation ?source_dimension ?dimension_value .
  }
}
UNION
{
   ?source_dimension a qb:DimensionProperty .
}
UNION
{
  ?source_dimension a qb:MeasureProperty .
}
UNION
{
  ?source_dimension a qb:CodedProperty .
}
} GROUP BY ?source_dimension LIMIT 1000
