#+ summary: basic hours worked query
#+ tags:
#+      - dwarsliggers
#+      - zandhuis

prefix medvar: <http://data.socialhistory.org/resource/med_clean/variable/>

SELECT ?volgnr ?weekuur
WHERE{
    ?medewerker medvar:ma_vm_aantal_uur ?ma_vm_aantal_uur .
    ?medewerker medvar:ma_nm_aantal_uur ?ma_nm_aantal_uur .
    ?medewerker medvar:di_vm_aantal_uur ?di_vm_aantal_uur .
    ?medewerker medvar:di_nm_aantal_uur ?di_nm_aantal_uur .
    ?medewerker medvar:wo_vm_aantal_uur ?wo_vm_aantal_uur .
    ?medewerker medvar:wo_nm_aantal_uur ?wo_nm_aantal_uur .
    BIND(?ma_vm_aantal_uur + ?ma_nm_aantal_uur + ?di_vm_aantal_uur + ?di_nm_aantal_uur + ?wo_vm_aantal_uur + ?wo_nm_aantal_uur AS ?weekuur) .
    ?medewerker medvar:volgnr ?volgnr .
}