#+ summary: avg. hours worked by marital status query
#+ tags:
#+      - dwarsliggers
#+      - zandhuis

prefix medvar: <http://data.socialhistory.org/resource/med_clean/variable/>
prefix bevvar: <http://data.socialhistory.org/resource/bev_clean/variable/>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?huw_st (AVG(?uren_week) AS ?avguur)
WHERE{
    ?medewerker medvar:ma_vm_aantal_uur ?ma_vm_aantal_uur .
    ?medewerker medvar:ma_nm_aantal_uur ?ma_nm_aantal_uur .
    ?medewerker medvar:di_vm_aantal_uur ?di_vm_aantal_uur .
    ?medewerker medvar:di_nm_aantal_uur ?di_nm_aantal_uur .
    ?medewerker medvar:di_nm_aantal_uur ?wo_nm_aantal_uur .
    ?medewerker medvar:di_nm_aantal_uur ?wo_vm_aantal_uur .
    BIND(xsd:integer(?ma_vm_aantal_uur) + xsd:integer(?ma_nm_aantal_uur) + xsd:integer(?di_vm_aantal_uur) + xsd:integer(?di_nm_aantal_uur) + xsd:integer(?wo_vm_aantal_uur) + xsd:integer(?wo_nm_aantal_uur) AS ?uren_week) .
    ?medewerker medvar:volgnr ?volgnr . 
	?bevperson bevvar:medewerker ?volgnr .
	?bevperson bevvar:huw_st ?huw_st .        
}
