#+ summary: gdp per capita trends for a country

PREFIX clioprop: <http://data.socialhistory.org/resource/clio/property/>
PREFIX clioind: <http://data.socialhistory.org/resource/clio/indicator/>
PREFIX clioctr: <http://data.socialhistory.org/resource/clio/country/>
PREFIX sdmxdim: <http://purl.org/linked-data/sdmx/2009/dimension#>
PREFIX sdmxmsr: <http://purl.org/linked-data/sdmx/2009/measure#>

SELECT ?year ?gdppc
FROM <http://data.socialhistory.org/resource/gdppc/assertion/5343176a06654392f04b0dcf163d1f1f0f65ffce/2015-12-15T17:24:38.636611>
WHERE{
  ?dataset clioprop:indicator clioind:GDPPC1990GKD .
  ?dataset sdmxdim:refArea ?_ctr .
  ?dataset sdmxdim:refPeriod ?year .
  ?dataset sdmxmsr:obsValue ?gdppc .
}
ORDER BY ASC(?year) ASC(?ctr)