#+ summary: gdp per capita trends for a country

prefix cliodim: <https://iisg.amsterdam/clio/dimension/>
PREFIX sdmxdim: <http://purl.org/linked-data/sdmx/2009/dimension#>
PREFIX sdmxmsr: <http://purl.org/linked-data/sdmx/2009/measure#>

SELECT ?year ?gdppc
WHERE{
  ?dataset sdmxdim:refArea ?_ctr .
  ?dataset sdmxdim:refPeriod ?year .
  ?dataset cliodim:GDP_per_Capita ?gdppc .
}
ORDER BY ASC(?year) ASC(?ctr)