#+ summary: parametrised age at life event query
#+ tags:
#+    - henry
#+    - life events

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX henry: <http://data.socialhistory.org/ns/resource/henry/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT * WHERE {
    ?parent henry:AN_NA_MA ?birthyear .
    ?parent ?pred ?year2 .
    # ?pred skos:definition ?_name_en
    ?pred skos:definition "year of the death of the husband"@en
    BIND(?year2 - ?birthyear AS ?age)
}