summary: give the HISCO category and source data for a given occupation
#+ tags:
#+      -hisco

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX hisco: <http://data.socialhistory.org/resource/hisco/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX prov: <http://www.w3.org/ns/prov#>

SELECT DISTINCT ?raw_label ?source ?hisco
WHERE {
  hisco:occupationalTitle skos:member ?occTitle .
  ?occtitle skos:altLabel ?raw_label .
  ?occtitle prov:wasDerivedFrom ?source .
  ?hisco rdf:type skos:Concept.
  ?hisco skos:member ?occtitle. 
  OPTIONAL {?occtitle skos:prefLabel ?raw_label } .
  FILTER regex(?raw_label, "^butcher", "i") .
}
LIMIT 10
