summary: show all occupations + hisco for a given language
#+ tags:
#+      - hisco

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX hisco: <http://data.socialhistory.org/vocab/hisco/>
PREFIX entry: <http://data.socialhistory.org/vocab/hisco/entry/>
PREFIX category: <http://data.socialhistory.org/vocab/hisco/category/>
PREFIX prov: <http://www.w3.org/ns/prov#>
## show all occupations for a given hisco

SELECT DISTINCT *
FROM <http://iisg.amsterdam/graph/hisco/open/v3/> 
WHERE { 
  ?entry skos:member entry:entryCollection . # entries in occupational fields are not always occupations
  ?entry skos:hiddenLabel ?raw_label . # all entries have a hiddenLabel
  ?entry skos:closeMatch ?hisco . # 
  FILTER (?hisco = category:54020)
  ?entry prov:wasQuotedFrom ?source .
  VALUES ?hisco {category:54020 category:56090} #only with SPARQL 1.1
  OPTIONAL {?entry skos:prefLabel ?clean_label} # not all occupational entries will have cleaned equivalents
  FILTER(lang(?raw_label) = "nl" && lang(?clean_label) = "nl")
} 
LIMIT 100
