#+ summary: query occupations coded in HISCO and their characteristics 
#+ tags:
#+      - hisco
#+      - hiscam

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX hiscam: <http://data.socialhistory.org/vocab/hiscam/>
PREFIX hisco: <http://data.socialhistory.org/vocab/hisco/>
PREFIX entry: <http://data.socialhistory.org/vocab/hisco/entry/>
PREFIX category: <http://data.socialhistory.org/vocab/hisco/category/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX qb: <http://purl.org/linked-data/cube#>


## show hiscam scores for a given hisco, the short and appropriate way
#
SELECT DISTINCT *
FROM <http://iisg.amsterdam/graph/hisco/open/v3/> 
WHERE { 
?entry skos:member entry:entryCollection . # entries in occupational fields are not always occupations
?entry skos:hiddenLabel ?raw_label . # all entries have a hiddenLabel
?entry skos:closeMatch ?hisco . # 
FILTER (?hisco = category:54020) .
          
# adding HISCAM values directly
?hisco hiscam:hiscamVersion.U1 ?hiscamU1 .
                
## OR appropriately (with more elaborate RDF options for HISCAM)
                    
?hiscamHisco skos:relatedMatch ?hisco .
?hiscamHisco hiscam:hiscamValue ?hiscamL . # links to all versions of HISCAM
?hiscamHisco qb:refArea hiscam:L. # selects specific version (but qb:refArea might not be best, as E and L stand for time periods)
                           
} 
LIMIT 100
