#+ summary: parametrised query to combine characteristic of individual observations with Clio data
#+ tags:
#+      - HSN
#+      - parametrised
#+      - GDP
#+      - clio


PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX hsndim: <http://data.socialhistory.org/resource/hsn/dimension/>
PREFIX hsn: <http://data.socialhistory.org/resource/hsn/>
PREFIX sdmxdim: <http://purl.org/linked-data/sdmx/2009/dimension#>
PREFIX cliomsr: <http://data.socialhistory.org/resource/clio/measure/>

SELECT *
FROM <http://data.socialhistory.org/resource/BEVDYNAP/assertion/7da40d05/2017-05-17T20:13>
FROM <http://data.socialhistory.org/ns/resource/GDP_Capita-historical/assertion/fd2ce578/2016-08-25T14:25>

WHERE {
    ?indiv hsndim:individualObservation ?obs1 .
    ?obs1 ?_dim1 ?var1 .
    ?obs1 hsndim:INGJAR ?year1 .
    ?obs1 hsndim:INGVLGNR ?vlgnr1 .

    ?gdpentry cliomsr:GDP_per_Capita ?gdp .
    ?gdpentry sdmxdim:refArea <http://data.socialhistory.org/resource/clio/Netherlands/1946/2012> .
    ?gdpentry sdmxdim:refPeriod ?year1  .
}
