#+ summary: hisclass over time for OPs
#+ tags:
#+      - HSN

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX hsndim: <http://data.socialhistory.org/resource/hsn/dimension/>
PREFIX hsn: <http://data.socialhistory.org/resource/hsn/>
PREFIX hsn-hisco: <http://data.socialhistory.org/resource/hsn2013a/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT ?person ?hisclass ?ingdat ?hisco
FROM <http://data.socialhistory.org/resource/BEVDYNAP/assertion/7da40d05/2017-05-17T20:13>
FROM <http://data.socialhistory.org/resource/hsn2013a_hisco_comma/assertion/fbedcdf7/2016-12-12T12:49>

WHERE{
    ?person hsndim:individualObservation ?obs .
    ?person a hsn:OP .
 
    ?obs hsndim:occstring_lc ?occlab .
    ?obs hsndim:IDNR ?idnr .
    ?obs hsndim:PERSNR ?persnr .
    ?obs hsndim:INGDAT ?ingdat .

    ?hisco skos:altLabel ?occlab .
    ?hisco hsn-hisco:hisclass ?hisclass .
}
