#+ summary: occupational status by religion over time
#+ tags:
#+      - HSN
#+      - religion
#+      - occupation
#+      - hisco
#+      - hisclass

# NB: hiscam preferable over hisclass, but timed out in earlier versions
# maybe fixable

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX hsndim: <http://data.socialhistory.org/resource/hsn/dimension/>
PREFIX hsn: <http://data.socialhistory.org/resource/hsn/>
PREFIX hsn-hisco: <http://data.socialhistory.org/resource/hsn2013a/>

SELECT *
FROM <http://data.socialhistory.org/resource/BEVDYNAP/assertion/7da40d05/2017-05-17T20:13>
FROM <http://data.socialhistory.org/resource/hsn2013a_hisco_comma/assertion/fbedcdf7/2016-12-12T12:49>
WHERE {
    ?indiv hsndim:individualObservation ?occobs .
    ?occobs hsndim:occupationalTitle ?occup .
    ?occobs hsndim:INGJAR ?occyear .
    ?occobs hsndim:INGVLGNR ?occno .

    ?occup hsn-hisco:hisclass ?hisclass .

    ?indiv hsndim:individualObservation ?relobs .
    ?relobs hsndim:Kerkgenootschap ?religie .
    ?relobs hsndim:INGVLGNR ?relno .

    FILTER(?relno = ?occno)
}
