#+ summary: father's occupation at birth of OPs who at some point live at non-family members
#+ tags:
#+      - HSN

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX hsndim: <http://data.socialhistory.org/resource/hsn/dimension/>
PREFIX hsn: <http://data.socialhistory.org/resource/hsn/>
PREFIX hsn-hisco: <http://data.socialhistory.org/resource/hsn2013a/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX sdmxdim: <http://purl.org/linked-data/sdmx/2009/dimension#>
prefix relacode: <http://data.socialhistory.org/resource/hsn/code/RELACODE/>

SELECT ?father ?fatherocc ?child ?childocc ?relhead
FROM <http://data.socialhistory.org/resource/BEVDYNAP/assertion/7da40d05/2017-05-17T20:13>
WHERE{
    ?child hsndim:inHousehold ?hh1 .
    ?child a hsn:OP .
    
    ?father hsndim:inHousehold ?hh1 .
    ?father hsndim:individualObservation/hsndim:relationToOP relacode:11 .  
    ?father hsndim:individualObservation ?fatherobs .
    ?fatherobs hsndim:occupationalTitle ?fatherocc .
    ?fatherobs hsndim:HUISHNR "1"^^xsd:string .
  
    ?child hsndim:inHousehold ?hh2 .
    ?child hsndim:individualObservation/hsndim:relationToHead ?relhead .
    VALUES ?relhead {relacode:41 relacode:42 relacode:43 relacode:48 relacode:90 relacode:94 relacode:91}
    ?child hsndim:individualObservation/hsndim:occupationalTitle ?childocc .
}
