#+ summary: All variables in the hub and the datasets using them
#+ pagination: 100
#+ tags:
#+      - overview

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX np: <http://www.nanopub.org/nschema#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX example: <http://www.example.org/rdf#>
PREFIX qb: <http://purl.org/linked-data/cube#>

SELECT DISTINCT ?source_dimension_a ?dim_lbl_a ?source_dimension_b ?dim_lbl_b  
WHERE {
{
  ?source_np np:hasAssertion ?source_assertion .
  GRAPH ?source_assertion {
   ?_sourcedataset_iri qb:structure/qb:component/(qb:dimension|qb:measure) ?source_dimension_a .
   ?observation_a ?source_dimension_a ?dimension_value_a .
   ?source_dimension_a rdfs:label ?dim_lbl_a .

   ?_sourcedataset_iri qb:structure/qb:component/(qb:dimension|qb:measure) ?source_dimension_b .
   ?observation_b ?source_dimension_b ?dimension_value_b .
   ?source_dimension_b rdfs:label ?dim_lbl_b .
  }
}
UNION
{
   ?source_dimension_a a qb:DimensionProperty .
   ?source_dimension_a rdfs:label ?dim_lbl_a .

   ?source_dimension_b a qb:DimensionProperty .
   ?source_dimension_b rdfs:label ?dim_lbl_b .
}
UNION
{
  ?source_dimension_a a qb:MeasureProperty .
  ?source_dimension_a rdfs:label ?dim_lbl_a .

  ?source_dimension_b a qb:MeasureProperty .
  ?source_dimension_b rdfs:label ?dim_lbl_b .
}
}
