PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX heightscountry: <https://iisg.amsterdam/microheights/code/country/>
PREFIX microheights: <https://iisg.amsterdam/microheights/>
PREFIX microdim: <https://iisg.amsterdam/microheights/dimension/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>


select ?cor ?iso_height ?country_cshapes ?cowdate ?observations  ?wktTooltip ?wktColor   {
  {
    select ?cowdate ?iso_height ?cor ?wkt ?country_cshapes (COUNT(distinct ?indiv) as ?observations) (avg(?height) as ?avg_height)  {
     {
  ?indiv microdim:ht_cm ?height .
  ?indiv microdim:bdec ?birthdecade .
  ?indiv microdim:age ?age .
  ?indiv microdim:countryOfResidence ?cor .
  ?cor microdim:isoAlpha2 ?iso_height .
  
  ?country_cshapes <https://iisg.amsterdam/vocab/isoAlpha2> ?iso_cshapes .
  ?country_cshapes <https://iisg.amsterdam/vocab/cowStart> ?cowdate .
  ?country_cshapes geo:hasGeometry / geo:asWKT ?wkt 
  
  BIND(STR(?iso_cshapes) as ?iso_cshapes2)
  FILTER(REGEX(?iso_height,  "[A-Z]"))
  FILTER(?iso_height = ?iso_cshapes2)
  FILTER (?cowdate != "1955-05-05"^^xsd:date)
        
   
  FILTER(?age > 19)
      }
    } 
  }
  bind((?avg_height) as ?wktTooltip)
  bind((bif:log((?observations / 58)) /  8) as ?observations2)
  bind(concat('viridis,', str(?observations2)) as ?wktColor) .
  
}
