#+ summary: age distribution for hungary
#+ tags:
#+      - mosaic

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX mosaicvrb: <http://data.socialhistory.org/ns/resource/variable/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT COUNT(?sub) ?age_num 
FROM <http://data.socialhistory.org/ns/vocab/datafile_152_version_1_0_labels_clean/assertion/7c710f8b/2016-04-26T18:19> 
WHERE {
    ?sub mosaicvrb:fname ?name .
    ?sub mosaicvrb:age ?age .
    BIND(xsd:int(STRAFTER(str(?age), "age/")) AS ?age_num) .
}
GROUP BY(?age_num)
ORDER BY(?age_num)
