#+ summary: young brides in mosaic data
#+ tags:
#+      - mosaic
#+      - patriarchy
#+      - young brides

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX mosaicvrb: <http://data.socialhistory.org/ns/resource/variable/>
PREFIX mosaicxtr: <http://data.socialhistory.org/ns/resource/variable/extra/>
PREFIX sex: <http://data.socialhistory.org/ns/resource/variable/sex/>
PREFIX relate: <http://data.socialhistory.org/ns/resource/variable/relate/>

SELECT  ?married (COUNT(?women) as ?n_women)
FROM <http://data.socialhistory.org/ns/vocab/datafile_152_version_1_0_labels_clean/assertion/7c710f8b/2016-04-26T18:19> 
WHERE {
    ?women mosaicvrb:sex sex:female .

    ?women mosaicxtr:age_num ?age .
    filter(?age >= 15 && ?age <= 19) .

    ?women mosaicvrb:marst ?marst .
    bind(if(contains(str(?marst), 'never'), 'unmarried', 'married') as ?married) .
}