#+ summary: variables in mosaic data
#+ tags:
#+      - mosaic
#+      - patriarchy
#+      - female non-kin in hh

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX mosaicvrb: <http://data.socialhistory.org/ns/resource/variable/>
PREFIX sex: <http://data.socialhistory.org/ns/resource/variable/sex/>
PREFIX relate: <http://data.socialhistory.org/ns/resource/variable/relate/>

SELECT  ?kin (COUNT(?women) as ?n_women)
FROM <http://data.socialhistory.org/ns/vocab/datafile_152_version_1_0_labels_clean/assertion/477126e3/2016-04-19T12:04> 
WHERE {
    # ?women mosaicvrb:sex sex:female .
    ?women mosaicvrb:relate ?relate .
    bind(if(regex(str(?relate), '(maid|room|lodg|empl|app|maid|cook|non)'), 'non kin', 'kin') as ?kin) .
    ?women mosaicvrb:age ?age .
    BIND(xsd:int(STRAFTER(STR(?age), "age/")) AS ?age_numeric) .
    filter(?age_numeric >= 20 && ?age_numeric <= 34) .
}
GROUP BY(?kin)