#+ summary: neolocals in mosaic data
#+ tags:
#+      - mosaic
#+      - patriarchy
#+      - neolocals

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX mosaicvrb: <http://data.socialhistory.org/ns/resource/variable/>
PREFIX mosaicxtr: <http://data.socialhistory.org/ns/resource/variable/extra/>
PREFIX sex: <http://data.socialhistory.org/ns/resource/variable/sex/>
PREFIX relate: <http://data.socialhistory.org/ns/resource/variable/relate/>

SELECT (COUNT(?men) as ?n_men) ?head
FROM <http://data.socialhistory.org/ns/vocab/datafile_152_version_1_0_labels_clean/assertion/7c710f8b/2016-04-26T18:19> 

WHERE{
    ?men mosaicvrb:sex sex:male .
    ?men mosaicxtr:age_num ?age .
    filter(?age >= 20 && ?age <= 29) .

    ?men mosaicvrb:relate ?relate .
    bind(if(contains(str(?relate), 'head'), 'head', 'not head') as ?head) .
}