# get mean by age as descriptive, 
# this time excluding orderdb:24
# as well as age = 999

PREFIX ordergb: <http://data.socialhistory.org/resource/napp/ORDERGB/>
PREFIX age: <http://data.socialhistory.org/resource/napp/AGE/>

SELECT (AVG(?occstatus) as ?mean_occstatus)  ?birthyear

FROM <http://data.socialhistory.org/resource/napp/dataset/englandwales1881> 
FROM <http://data.socialhistory.org/resource/napp/>

WHERE{
    ?s napp-dimension:ORDERGB ?ordergb .
    ?s napp-dimension:AGE ?age .
    ?s napp-dimension:YEAR ?year .
    BIND(?year - ?age AS ?birthyear)
    ?ordergb rdf:value ?occstatus .
    FILTER(?occstatus != 24 || ?age != '999')
}

GROUP BY ?birthyear
ORDER BY ?birthyear