#---- query 11 -----#
# obtain the individual-level dataset
# combined with gdp in birthyear data
# similar to query 10, but without the average aggregation of occstatus
# currently querying small dataset
# endpoint = http://virtuoso.kdr250.eculture.labs.vu.nl/sparql

PREFIX ordergb: <http://data.socialhistory.org/resource/napp/ORDERGB/>
PREFIX nappclioctr: <http://data.socialhistory.org/resource/napp/BPLCNTRY/>
PREFIX napp-dimension: <http://data.socialhistory.org/vocab/napp/dimension/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX sdmx-dimension: <http://purl.org/linked-data/sdmx/2009/dimension#>
PREFIX clioprop: <http://data.socialhistory.org/resource/clio/property/>
PREFIX sdmx-measure: <http://purl.org/linked-data/sdmx/2009/measure#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?age ?birthyear ?occstatus ?gdppc ?county ?birthcountry ?maritalstat ?sex ?urban 

FROM <http://data.socialhistory.org/resource/napp/dataset/englandwales1881>
FROM <http://data.socialhistory.org/resource/napp/>

WHERE {
    ?personid napp-dimension:ORDERGB ?ordergb .
    ?ordergb rdf:value ?occstatus .
    ?personid napp-dimension:AGE ?age .
    FILTER(?occstatus != 24 || ?age != '999')
    ?personid napp-dimension:YEAR ?year .

    # additional control variables, still to be de-uri'd & minus'd
    ?personid napp-dimension:COUNTYGB ?county .
    ?personid napp-dimension:BPLCNTRY ?birthcountry .
    ?personid napp-dimension:SEX ?sex .
    ?personid napp-dimension:URBAN ?urban .
    FILTER(?birthcountry != nappclioctr:99999)
    ?personid napp-dimension:MARST ?maritalstat
    BIND(?year - ?age AS ?birthyear) .
    {
        SELECT ?birthyear ?gdppc 
		FROM <http://data.socialhistory.org/resource/gdppc/assertion/5343176a06654392f04b0dcf163d1f1f0f65ffce/2015-12-09T16:42:52.541256>
        WHERE {
            ?data sdmx-dimension:refArea clioctr:826 .
            ?data sdmx-dimension:refPeriod ?year .
            ?data clioprop:indicator clioind:GDPPC1990GKD .
            ?data sdmx-measure:obsValue ?gdppc .
            BIND(xsd:integer(str(?year)) AS ?birthyear) .
        }
    }
}

LIMIT 100
