# inspect data because 0 gets a (high) average occupational status

PREFIX napp-dimension: <http://data.socialhistory.org/vocab/napp/dimension/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?occstatus ?age

FROM <http://data.socialhistory.org/resource/napp/dataset/englandwales1881>
FROM <http://data.socialhistory.org/resource/napp/>

WHERE{
    ?s napp-dimension:ORDERGB ?ordergb .
    ?ordergb rdf:value ?occstatus . 
    ?s napp-dimension:AGE ?age.
    VALUES ?age{0 10 20 80}
}

ORDER BY ?age
LIMIT 100 
