# ----- qry10 -------#
# average occstatus by birthyear
# linked to british gdp from clio-datacube

# goal is to get occupation status by birthyear
# ideally occupational status would come from hisco -> hiscam mapping
# and has birthyear linked to gdp data (better yet; gdp at county/region level)

# query on clio-gdp using worldbank datacube structure (more or less)
# endpoint = http://virtuoso.kdr250.eculture.labs.vu.nl/sparql


PREFIX ordergb: <http://data.socialhistory.org/resource/napp/ORDERGB/>
PREFIX napp-dimension: <http://data.socialhistory.org/vocab/napp/dimension/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX sdmx-dimension: <http://purl.org/linked-data/sdmx/2009/dimension#>
PREFIX clioprop: <http://data.socialhistory.org/resource/clio/property/>
PREFIX sdmx-measure: <http://purl.org/linked-data/sdmx/2009/measure#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT ?birthyear ?gdp ?mean_occstatus

FROM <http://data.socialhistory.org/resource/gdppc/assertion/5343176a06654392f04b0dcf163d1f1f0f65ffce/2015-12-09T16:42:52.541256>

WHERE {
	?dataset sdmx-dimension:refArea clioctr:826 .
	?dataset sdmx-dimension:refPeriod ?year .
	?dataset clioprop:indicator clioind:GDPPC1990GKD .
	?dataset sdmx-measure:obsValue ?gdp .
	
	# difficult to remove this bind!? 
	BIND(xsd:integer(STR(?year)) AS ?birthyear)

    { SELECT (AVG(?occstatus) as ?mean_occstatus) ?birthyear
	
	FROM <http://data.socialhistory.org/resource/napp/dataset/englandwales1881>
	FROM <http://data.socialhistory.org/resource/napp/>
	
		WHERE {
		?s napp-dimension:ORDERGB ?ordergb .
        ?ordergb rdf:value ?occstatus .
		?s napp-dimension:AGE ?age .
		FILTER(?occstatus != 24 || ?age != '999')
		?s napp-dimension:YEAR ?year .
		BIND(?year - ?age AS ?birthyear)
      }
      GROUP BY ?birthyear
    }
}

ORDER BY ?birthyear
