# get mean by age as check for data

PREFIX dim: <http://data.socialhistory.org/vocab/napp/dimension/>

SELECT (ROUND(AVG(?occstatus)) as ?mean_occstatus) ?age 

FROM <http://data.socialhistory.org/resource/napp/dataset/englandwales1881> 
FROM <http://data.socialhistory.org/resource/napp/>

WHERE{
    ?s dim:ORDERGB ?ordergb .
    ?ordergb rdf:value ?occstatus . 
    ?s dim:AGE ?age .
}

GROUP BY ?age
ORDER BY ?age