# inspect data because 0 gets a (high) average occupational status

SELECT ?occstatus ?age

FROM <http://data.socialhistory.org/resource/napp/dataset/englandwales1881>
FROM <http://data.socialhistory.org/resource/napp/>

WHERE{
    ?s napp-dimension:ORDERGB ?ordergb .
    ?ordergb rdf:value ?occstatus . 
    ?s napp-dimension:AGE ?age.
    VALUES ?age{0 10 20 80}
}

ORDER BY ?age
LIMIT 100 