# little test-query to see how to filter/minus on literal

SELECT DISTINCT ?age

FROM <http://data.socialhistory.org/resource/napp/dataset/englandwales1881> 

WHERE{
    ?s napp-dimension:AGE ?age .
    FILTER(?age != '999')
}

ORDER BY ?age