# get ordergb by birth year

PREFIX dim: <http://data.socialhistory.org/vocab/napp/dimension/>

SELECT ?occstatus ?year ?age ?birthyear ?county 

FROM <http://data.socialhistory.org/resource/napp/dataset/englandwales1881> 

WHERE{
    ?s dim:ORDERGB ?ordergb .
    BIND(xsd:integer(STRAFTER(STR(?ordergb), 'ORDERGB/')) AS ?occstatus)
    ?s dim:COUNTYGB ?county .
    ?s dim:YEAR ?year.
    ?s dim:AGE ?age .
    BIND(xsd:integer(?year) - xsd:integer(?age) AS ?birthyear) .
}

LIMIT 100 