# get mean by age as descriptive, 
# this time excluding orderdb:24
# as well as age = 999

PREFIX dim: <http://data.socialhistory.org/vocab/napp/dimension/>
PREFIX ordergb: <http://data.socialhistory.org/resource/napp/ORDERGB/>
PREFIX age: <http://data.socialhistory.org/resource/napp/AGE/>

SELECT (AVG(?occstatus) as ?mean_occstatus)  ?birthyear

FROM <http://data.socialhistory.org/resource/napp/dataset/englandwales1881> 
FROM <http://data.socialhistory.org/resource/napp/>

WHERE{
    ?s dim:ORDERGB ?ordergb .
    ?s dim:AGE ?age .
    ?s dim:YEAR ?year .
    BIND(xsd:integer(?year) - xsd:integer(?age) AS ?birthyear)
    ?ordergb rdf:value ?occstatus .
    FILTER(?occstatus != 24 || ?age != '999')
}

GROUP BY ?birthyear
ORDER BY ?birthyear