# query for individual-level dataset with some controls
# all these variables should also be investigated for missing codes etc.

PREFIX ordergb: <http://data.socialhistory.org/resource/napp/ORDERGB/>
PREFIX age: <http://data.socialhistory.org/resource/napp/AGE/>
PREFIX napp-dimension: <http://data.socialhistory.org/vocab/napp/dimension/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?year ?age ?ordergb ?occstatus ?birthyear 
    ?county ?birthcounty ?birthcountry ?marst ?labforce ?sex ?urban
    
FROM <http://data.socialhistory.org/resource/napp/dataset/englandwales1881>
FROM <http://data.socialhistory.org/resource/napp/>

WHERE{
    ?s napp-dimension:AGE ?age .
    ?s napp-dimension:ORDERGB ?ordergb .
    ?ordergb rdf:value ?occstatus .
    ?s napp-dimension:YEAR ?year .
    ?s napp-dimension:COUNTYGB ?county .
    # ?county skos:prefLabel ?countyname # vocab with preflabels not present
    ?s napp-dimension:BPLCNTRY ?birthcountry .
    ?s napp-dimension:BPLCTYGB ?birthcounty .
    ?s napp-dimension:MARST ?marst .
    ?s napp-dimension:LABFORCE ?labforce .
    ?s napp-dimension:SEX ?sex .
    ?s napp-dimension:URBAN ?urban .
    FILTER(?occstatus != 24 || ?age != '999')
    BIND(?year - ?age AS ?birthyear)
}

LIMIT 100 
