# get ordergb by birth year

SELECT ?occstatus ?year ?age ?birthyear ?county 

FROM <http://data.socialhistory.org/resource/napp/dataset/englandwales1881> 
FROM <http://data.socialhistory.org/resource/napp/>

WHERE{
    ?s napp-dimension:ORDERGB ?ordergb .
    ?ordergb rdf:value ?occstatus . 
    ?s napp-dimension:COUNTYGB ?county .
    ?s napp-dimension:YEAR ?year.
    ?s napp-dimension:AGE ?age .
    BIND(?year - ?age AS ?birthyear) .
}

LIMIT 100 