# get mean by age as check for data

SELECT (ROUND(AVG(?occstatus)) as ?mean_occstatus) ?age 

FROM <http://data.socialhistory.org/resource/napp/dataset/englandwales1881> 
FROM <http://data.socialhistory.org/resource/napp/>

WHERE{
    ?s napp-dimension:ORDERGB ?ordergb .
    ?ordergb rdf:value ?occstatus . 
    ?s napp-dimension:AGE ?age .
}

GROUP BY ?age
ORDER BY ?age