#+ summary: counts occupations of spanjestrijders using hisco codes
#+ tags:
#+      - spanjestrijders
#+      - occupations
#+      - hisco
#+      - hisclass

#+ endpoint: https://api.druid.datalegend.net/datasets/RubenS/Spanjestrijders-test/services/Spanjestrijders-test/sparql

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX spanjestrijders: <https://iisg.amsterdam/spanjestrijders/dimension/>
PREFIX hsn: <https://iisg.amsterdam/hsn2013a/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT (count(?beroep) as ?n_beroep) ?beroep ?hisclass WHERE {
    ?spanjestrijder spanjestrijders:Beroep ?beroep .
    ?beroep skos:exactMatch / hsn:hisclass ?hisclass .
 
  # get hisco code:
  ?hisco skos:member ?hsnberoep .
  ?hisco skos:notation ?hisconr.
} 
ORDER BY DESC (?n_beroep)
