PREFIX napp-dimension: <http://data.socialhistory.org/vocab/napp/dimension/>
PREFIX relate: <http://data.socialhistory.org/resource/napp/RELATE/>

SELECT (COUNT(DISTINCT ?householdID) as ?count) 

FROM <http://data.socialhistory.org/resource/napp/dataset/englandwales1881>

WHERE{

    VALUES ?child1_relate { relate:301 relate:302 relate:306 }
    VALUES ?child2_relate { relate:301 relate:302 relate:306 }
  
    ?child1 napp-dimension:SERIAL ?householdID .
    ?child2 napp-dimension:SERIAL ?householdID .

    ?child1 napp-dimension:AGE ?age .
    ?child2 napp-dimension:AGE ?age .   

    ?child1 napp-dimension:RELATE ?child1_relate .

    ?child2 napp-dimension:RELATE ?child2_relate .

    FILTER (?child1 != ?child2)
}