PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX schema: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX hdng: <https://iisg.amsterdam/hdng/>
PREFIX hdngv: <https://iisg.amsterdam/hdng/vocab/>
PREFIX hdngvar: <https://iisg.amsterdam/hdng/variable/>
PREFIX gg: <http://www.gemeentegeschiedenis.nl/gg-schema#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>

SELECT DISTINCT ?variable ?variable_name ?category ?specification (min(?year) as ?min_year) (max(?year) as ?max_year) WHERE {
 
  
  ?variable a hdng:variable.
  ?variable hdngv:variableName ?variable_name .
  ?variable hdngv:category ?category .
  ?variable hdngv:specification ?specification.
  ?variable schema:hasObservation/ hdngv:year ?year .
  
  
} 

ORDER BY (?variable)
