PREFIX candim: <http://data.socialhistory.org/vocab/canfam/dimension/>
PREFIX rdf:	<http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX auke-religion: <http://data.socialhistory.org/resource/canfam/auke/religion/>


INSERT { 

    GRAPH <http://data.socialhistory.org/resource/canfam/auke> { 

        ?otherreligion auke-religion: auke-religion:other . 

     } 
}

WHERE { 

    GRAPH <http://data.socialhistory.org/resource/canfam/dataset/canada1901> { 

        ?so candim:religio2 ?otherreligion .
        ?otherreligion rdf:value ?otherreligionvalue . 
        FILTER(?otherreligionvalue >= 20) . 
        
    } 
}
